# Form implementation generated from reading ui file 'interface_test.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet(".QMainWindow{background-color:gray;}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.createAccTable = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.createAccTable.setGeometry(QtCore.QRect(150, 80, 481, 371))
        self.createAccTable.setAutoFillBackground(False)
        self.createAccTable.setStyleSheet("QLineEdit{border-radius: 4px;\n"
                                         "border-style: solid;\n"
                                         "border-width: 1px;\n"
                                         "border-color: gray;}\n"
                                         "QLabel{color:;}\n"
                                         "QWidget{background-color:}\n"
                                         "QTabBar {color:;}\n"
                                         "QPalette {color:;}\n"
                                         "QAbstractButton{color:;}")
        self.createAccTable.setObjectName("createAccTabe")
        self.createTab = QtWidgets.QWidget()
        self.createTab.setObjectName("createTab")
        self.firstName = QtWidgets.QLineEdit(parent=self.createTab)
        self.firstName.setGeometry(QtCore.QRect(30, 90, 101, 22))
        self.firstName.setStyleSheet("QLineEdit::placeholder {color: red;\n}")
        self.firstName.setObjectName("firstName")
        self.userEmail = QtWidgets.QLineEdit(parent=self.createTab)
        self.userEmail.setGeometry(QtCore.QRect(30, 140, 141, 22))
        self.userEmail.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.userEmail.setObjectName("userEmail")
        self.username = QtWidgets.QLineEdit(parent=self.createTab)
        self.username.setGeometry(QtCore.QRect(30, 190, 141, 22))
        self.username.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.username.setObjectName("username")
        self.userPassword = QtWidgets.QLineEdit(parent=self.createTab)
        self.userPassword.setGeometry(QtCore.QRect(30, 240, 141, 22))
        self.userPassword.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.userPassword.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.userPassword.setText("")
        self.userPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.userPassword.setObjectName("userPassword")
        self.lastName = QtWidgets.QLineEdit(parent=self.createTab)
        self.lastName.setGeometry(QtCore.QRect(150, 90, 101, 22))
        self.lastName.setObjectName("lastName")
        self.createAccLabel = QtWidgets.QLabel(parent=self.createTab)
        self.createAccLabel.setGeometry(QtCore.QRect(140, 30, 178, 32))
        self.createAccLabel.setStyleSheet("#createAccLabel {font-family: Arial, Helvetica, sans-serif;\n"
                                          "font-size: 28pt;}\n")
        self.createAccLabel.setObjectName("createAccLabel")
        self.companyName = QtWidgets.QLineEdit(parent=self.createTab)
        self.companyName.setGeometry(QtCore.QRect(30, 290, 141, 22))
        self.companyName.setObjectName("companyName")
        self.enterButton = QtWidgets.QPushButton(parent=self.createTab)
        self.enterButton.setGeometry(QtCore.QRect(330, 290, 121, 31))
        self.enterButton.setObjectName("enterButton")
        self.createAccTable.addTab(self.createTab, "")
        self.loginTab = QtWidgets.QWidget()
        self.loginTab.setObjectName("loginTab")
        self.loginLabel = QtWidgets.QLabel(parent=self.loginTab)
        self.loginLabel.setGeometry(QtCore.QRect(130, 40, 197, 32))
        self.loginLabel.setStyleSheet(".QLabel{font-size:28pt; font-family: Arial, Helvetica, sans-serif;}")
        self.loginLabel.setObjectName("loginLabel")
        self.username_login = QtWidgets.QLineEdit(parent=self.loginTab)
        self.username_login.setGeometry(QtCore.QRect(170, 140, 113, 22))
        self.username_login.setObjectName("username_login")
        self.passwordLogin = QtWidgets.QLineEdit(parent=self.loginTab)
        self.passwordLogin.setGeometry(QtCore.QRect(170, 200, 113, 22))
        self.passwordLogin.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordLogin.setObjectName("passwordLogin")
        self.login_enter = QtWidgets.QPushButton(parent=self.loginTab)
        self.login_enter.setGeometry(QtCore.QRect(180, 280, 91, 31))
        self.login_enter.setObjectName("login_enter")
        self.createAccTable.addTab(self.loginTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.createAccTable.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.firstName.setPlaceholderText(_translate("MainWindow", "firstname"))
        self.userEmail.setPlaceholderText(_translate("MainWindow", "email"))
        self.username.setPlaceholderText(_translate("MainWindow", "username"))
        self.userPassword.setPlaceholderText(_translate("MainWindow", "password"))
        self.lastName.setPlaceholderText(_translate("MainWindow", "lastname"))
        self.createAccLabel.setText(_translate("MainWindow", "Create Acount"))
        self.createAccLabel.adjustSize()
        self.companyName.setPlaceholderText(_translate("MainWindow", "company name"))
        self.enterButton.setText(_translate("MainWindow", "Confirm"))
        self.createAccTable.setTabText(self.createAccTable.indexOf(self.createTab), _translate("MainWindow", "Create Account"))
        self.loginLabel.setText(_translate("MainWindow", "Company Login"))
        self.loginLabel.adjustSize()
        self.username_login.setPlaceholderText(_translate("MainWindow", "username"))
        self.passwordLogin.setPlaceholderText(_translate("MainWindow", "password"))
        self.login_enter.setText(_translate("MainWindow", "Enter"))
        self.createAccTable.setTabText(self.createAccTable.indexOf(self.loginTab), _translate("MainWindow", "Login"))
